version: '3.3'
services:
  db:
    image: mysql:5.7
    restart: always

    # these will be the environment variables used inside the container
    environment:
      MYSQL_DATABASE: 'projectdb'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'julio'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password123'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password123'

    ports:
      # host<Port exposed> : container< MySQL Port running inside container>
      - '3306:3306'

    expose:
      # Opens port 3306 on the container
      - '3306'

    # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql

volumes:
  my-db: